TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

INC += GenICamFeature.h

LIBRARY_IOC += ADGenICAM

LIB_SRCS += GenICamFeature.cpp
#LIB_SRCS += ADGenICam.cpp

include $(ADCORE)/ADApp/commonLibraryMakefile

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

