TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

INC += GenICamFeature.h
INC += ADGenICam.h

LIBRARY_IOC += ADGenICam

LIB_SRCS += GenICamFeature.cpp
LIB_SRCS += ADGenICam.cpp

include $(ADCORE)/ADApp/commonLibraryMakefile

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

